In [1]:
import pandas as pd
data = pd.read_csv('selected_data_v2.csv')

In [2]:
data

,business_id,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking,stars
0,IbuSlumTCNSD-ohMVHfWUA,5.0,0.556776,4.536000,4.771429,4.569231,2.0,Greek,50.0,1.0,1.0,4.0
1,mAM8m5iXalmqmFT6aQsyZA,4.0,1.308274,3.693846,3.528571,3.843182,3.0,American (,410.0,1.0,1.0,3.5
2,mAM8m5iXalmqmFT6aQsyZA,4.0,1.308274,3.693846,3.528571,3.843182,3.0,Vietnamese,410.0,1.0,1.0,3.5
3,2AORsy2N2kbFX91EXm10Qg,5.0,1.106408,4.605263,4.884615,4.925000,3.0,Italian,371.0,1.0,1.0,4.0
4,RYzWC7G9p53Qd_LcYWqOkA,2.5,1.537731,2.634615,2.527778,2.730769,1.0,American (,113.0,1.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
21108,gyVmxr4RsrZQuF0xwCyHDQ,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Chinese,97.0,1.0,1.0,3.0
21109,gyVmxr4RsrZQuF0xwCyHDQ,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Vietnamese,97.0,1.0,1.0,3.0
21110,sjrlIjfbLsN0mez4zZ8Hlg,2.5,2.121320,2.500000,2.500000,2.500000,1.0,French,50.0,1.0,1.0,3.5
21111,iwZwJMgYr5V5rCrD3qJ3aA,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Japanese,52.0,1.0,1.0,4.5
21112,iwZwJMgYr5V5rCrD3qJ3aA,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Korean,52.0,1.0,1.0,4.5

In [ ]:
for i in range(len(data['categories'])):
    if data['categories'][i] =='American (':
        data['categories'][i] = 'American'

In [4]:
data

,business_id,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking,stars
0,IbuSlumTCNSD-ohMVHfWUA,5.0,0.556776,4.536000,4.771429,4.569231,2.0,Greek,50.0,1.0,1.0,4.0
1,mAM8m5iXalmqmFT6aQsyZA,4.0,1.308274,3.693846,3.528571,3.843182,3.0,American,410.0,1.0,1.0,3.5
2,mAM8m5iXalmqmFT6aQsyZA,4.0,1.308274,3.693846,3.528571,3.843182,3.0,Vietnamese,410.0,1.0,1.0,3.5
3,2AORsy2N2kbFX91EXm10Qg,5.0,1.106408,4.605263,4.884615,4.925000,3.0,Italian,371.0,1.0,1.0,4.0
4,RYzWC7G9p53Qd_LcYWqOkA,2.5,1.537731,2.634615,2.527778,2.730769,1.0,American,113.0,1.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
21108,gyVmxr4RsrZQuF0xwCyHDQ,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Chinese,97.0,1.0,1.0,3.0
21109,gyVmxr4RsrZQuF0xwCyHDQ,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Vietnamese,97.0,1.0,1.0,3.0
21110,sjrlIjfbLsN0mez4zZ8Hlg,2.5,2.121320,2.500000,2.500000,2.500000,1.0,French,50.0,1.0,1.0,3.5
21111,iwZwJMgYr5V5rCrD3qJ3aA,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Japanese,52.0,1.0,1.0,4.5
21112,iwZwJMgYr5V5rCrD3qJ3aA,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Korean,52.0,1.0,1.0,4.5

In [525]:
ls = []
for i in range(len(data['categories'])):
    if data['categories'][i] =='American':
        ls .append(i)

In [526]:
data = data.drop(ls)

In [527]:
data.to_csv('selected_data2.csv')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
m = data.pop('stars')

In [7]:
m

0        4.0
1        3.5
2        3.5
3        4.0
4        3.0
        ...
21108    3.0
21109    3.0
21110    3.5
21111    4.5
21112    4.5
Name: stars, Length: 21113, dtype: float64

In [8]:
#labels encoding
y = []
for i in m:
    if i<3:
        y.append(0)
    elif i<=4:
        y.append(1)
    elif i<=5:
        y.append(2)

In [9]:
data.pop('business_id')

0        IbuSlumTCNSD-ohMVHfWUA
1        mAM8m5iXalmqmFT6aQsyZA
2        mAM8m5iXalmqmFT6aQsyZA
3        2AORsy2N2kbFX91EXm10Qg
4        RYzWC7G9p53Qd_LcYWqOkA
                  ...
21108    gyVmxr4RsrZQuF0xwCyHDQ
21109    gyVmxr4RsrZQuF0xwCyHDQ
21110    sjrlIjfbLsN0mez4zZ8Hlg
21111    iwZwJMgYr5V5rCrD3qJ3aA
21112    iwZwJMgYr5V5rCrD3qJ3aA
Name: business_id, Length: 21113, dtype: object

In [10]:
x = data

In [11]:
x

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking
0,5.0,0.556776,4.536000,4.771429,4.569231,2.0,Greek,50.0,1.0,1.0
1,4.0,1.308274,3.693846,3.528571,3.843182,3.0,American,410.0,1.0,1.0
2,4.0,1.308274,3.693846,3.528571,3.843182,3.0,Vietnamese,410.0,1.0,1.0
3,5.0,1.106408,4.605263,4.884615,4.925000,3.0,Italian,371.0,1.0,1.0
4,2.5,1.537731,2.634615,2.527778,2.730769,1.0,American,113.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
21108,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Chinese,97.0,1.0,1.0
21109,2.0,1.281740,3.222222,2.250000,2.785714,0.0,Vietnamese,97.0,1.0,1.0
21110,2.5,2.121320,2.500000,2.500000,2.500000,1.0,French,50.0,1.0,1.0
21111,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Japanese,52.0,1.0,1.0
21112,5.0,0.447214,4.800000,4.800000,4.960000,1.0,Korean,52.0,1.0,1.0

In [12]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [13]:

from imblearn.over_sampling import SMOTE

Upsampling: SMOTE

In [14]:
X_train

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking
20037,1.0,1.127063,1.334630,1.553191,2.191489,2.0,American,125.0,1.0,1.0
17594,2.0,1.578261,3.904762,4.195122,2.322581,0.0,Chinese,61.0,1.0,1.0
12633,5.0,0.965532,4.419417,4.027907,4.376471,0.0,Italian,683.0,1.0,1.0
17737,3.5,1.211060,3.125000,3.333333,3.750000,0.0,Canadian,60.0,1.0,1.0
3758,4.0,1.477790,4.250000,3.937500,3.661765,1.0,American,187.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
19005,5.0,1.087811,4.438776,4.210526,4.433962,5.0,Italian,127.0,1.0,1.0
6979,4.0,1.603567,3.859813,3.893617,3.893617,0.0,Indian,30.0,1.0,1.0
4866,4.0,0.577350,3.666667,3.666667,3.666667,1.0,Italian,21.0,1.0,1.0
16898,4.0,1.400655,3.792490,3.776786,3.843750,2.0,American,703.0,1.0,1.0
11273,5.0,0.000000,5.000000,5.000000,5.000000,0.0,American,10.0,1.0,1.0

In [15]:
y_train

[0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 2,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [16]:
import copy
df = copy.deepcopy(X_train)

In [17]:
df

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking
20037,1.0,1.127063,1.334630,1.553191,2.191489,2.0,American,125.0,1.0,1.0
17594,2.0,1.578261,3.904762,4.195122,2.322581,0.0,Chinese,61.0,1.0,1.0
12633,5.0,0.965532,4.419417,4.027907,4.376471,0.0,Italian,683.0,1.0,1.0
17737,3.5,1.211060,3.125000,3.333333,3.750000,0.0,Canadian,60.0,1.0,1.0
3758,4.0,1.477790,4.250000,3.937500,3.661765,1.0,American,187.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
19005,5.0,1.087811,4.438776,4.210526,4.433962,5.0,Italian,127.0,1.0,1.0
6979,4.0,1.603567,3.859813,3.893617,3.893617,0.0,Indian,30.0,1.0,1.0
4866,4.0,0.577350,3.666667,3.666667,3.666667,1.0,Italian,21.0,1.0,1.0
16898,4.0,1.400655,3.792490,3.776786,3.843750,2.0,American,703.0,1.0,1.0
11273,5.0,0.000000,5.000000,5.000000,5.000000,0.0,American,10.0,1.0,1.0

In [18]:
df['stars'] = y_train

In [19]:
y_smote = df.pop('categories')

In [20]:
x_smote = df

In [21]:
x_smote

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,review_count,restaurants_take_out,business_parking,stars
20037,1.0,1.127063,1.334630,1.553191,2.191489,2.0,125.0,1.0,1.0,0
17594,2.0,1.578261,3.904762,4.195122,2.322581,0.0,61.0,1.0,1.0,1
12633,5.0,0.965532,4.419417,4.027907,4.376471,0.0,683.0,1.0,1.0,1
17737,3.5,1.211060,3.125000,3.333333,3.750000,0.0,60.0,1.0,1.0,1
3758,4.0,1.477790,4.250000,3.937500,3.661765,1.0,187.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...
19005,5.0,1.087811,4.438776,4.210526,4.433962,5.0,127.0,1.0,1.0,1
6979,4.0,1.603567,3.859813,3.893617,3.893617,0.0,30.0,1.0,1.0,0
4866,4.0,0.577350,3.666667,3.666667,3.666667,1.0,21.0,1.0,1.0,1
16898,4.0,1.400655,3.792490,3.776786,3.843750,2.0,703.0,1.0,1.0,1
11273,5.0,0.000000,5.000000,5.000000,5.000000,0.0,10.0,1.0,1.0,1

In [22]:
smo = SMOTE(random_state=42)
x_smo, y_smo = smo.fit_resample(x_smote, y_smote)

In [23]:
df_smo = pd.concat([x_smo, y_smo],axis = 1)

In [24]:
y_train2 = df_smo.pop('stars')

In [25]:
x_train2 = df_smo

In [26]:
x_train2.to_csv('x_train2.csv')

In [27]:
x_train2

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,review_count,restaurants_take_out,business_parking,categories
0,1.000000,1.127063,1.334630,1.553191,2.191489,2.000000,125.000000,1.000000,1.000000,American
1,2.000000,1.578261,3.904762,4.195122,2.322581,0.000000,61.000000,1.000000,1.000000,Chinese
2,5.000000,0.965532,4.419417,4.027907,4.376471,0.000000,683.000000,1.000000,1.000000,Italian
3,3.500000,1.211060,3.125000,3.333333,3.750000,0.000000,60.000000,1.000000,1.000000,Canadian
4,4.000000,1.477790,4.250000,3.937500,3.661765,1.000000,187.000000,1.000000,1.000000,American
...,...,...,...,...,...,...,...,...,...,...
70919,4.775410,1.087713,3.621566,3.738183,4.422515,5.550819,195.000000,1.000000,1.000000,Vietnamese
70920,4.285342,1.225197,4.377369,3.988194,4.304958,1.287950,19.000000,0.429317,0.000000,Vietnamese
70921,4.239295,1.028930,4.263888,3.949387,4.180291,3.282114,155.000000,1.000000,1.000000,Vietnamese
70922,3.850137,1.730605,3.196695,1.717074,3.196695,1.000000,32.149863,1.000000,0.000000,Vietnamese
70923,4.285914,1.106201,3.330006,3.491448,3.646119,1.571829,103.428171,1.000000,0.428171,Vietnamese

In [28]:
X_test

,review_stars_median,review_stars_std,weighted_useful_stars,weighted_funny_stars,weighted_cool_stars,tip_cnt,categories,review_count,restaurants_take_out,business_parking
19389,4.0,1.342077,2.949153,3.368421,3.368421,1.0,Japanese,223.0,1.0,1.0
2075,4.0,1.928673,1.490385,1.484375,2.291667,0.0,Italian,244.0,1.0,1.0
8397,4.5,1.880925,3.257937,2.068627,3.492424,0.0,Chinese,136.0,1.0,1.0
17924,4.0,1.398051,3.183673,2.842105,3.538462,4.0,Indian,415.0,1.0,1.0
19919,1.0,1.388730,1.085308,1.162162,1.439024,1.0,Italian,125.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
10283,5.0,0.000000,5.000000,5.000000,5.000000,0.0,American,191.0,1.0,1.0
2070,5.0,0.663325,4.585185,4.446154,4.511111,1.0,Mexican,42.0,1.0,1.0
3283,4.0,1.414214,3.440678,3.666667,3.666667,2.0,Japanese,115.0,1.0,1.0
7926,4.0,0.000000,4.000000,4.000000,4.000000,0.0,Italian,14.0,1.0,0.0
17082,2.0,2.081666,3.878788,1.384615,2.666667,1.0,Japanese,22.0,1.0,1.0

In [29]:
y_train2.to_csv('y_train2.csv')

In [30]:
X_test.to_csv('x_test2.csv')

In [31]:
pd.DataFrame(y_test).to_csv('y_test2.csv')